/*
 * Copyright (C) 2022 Diego Andrés Gutiérrez Berón
 * 
 * Some parts of this software were made as adaptations of ideas other than mine.
 * In any case, due credit is given for any ideas or code that served as an
 * implementation base for this software.
 *
 * THIS PROGRAM IS LICENSED UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package dialogs;

import emulator.Chip8_CPU;
import java.awt.Component;
import java.awt.Container;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author Diego Gutierrez
 */
public class StatusDialog extends javax.swing.JDialog {

    private Chip8_CPU cpu;

    /**
     * Creates new form StatusDialog
     */
    public StatusDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listMemoryPanels = (ArrayList<MemoryPanel>) getAllMemoryPanelComponents(jPanel1);
        nOfPanels = listMemoryPanels.size();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        v0Value = new javax.swing.JTextField();
        v1Value = new javax.swing.JTextField();
        v2Value = new javax.swing.JTextField();
        v3Value = new javax.swing.JTextField();
        v4Value = new javax.swing.JTextField();
        v5Value = new javax.swing.JTextField();
        v6Value = new javax.swing.JTextField();
        v7Value = new javax.swing.JTextField();
        v8Value = new javax.swing.JTextField();
        v9Value = new javax.swing.JTextField();
        vAValue = new javax.swing.JTextField();
        vBValue = new javax.swing.JTextField();
        vCValue = new javax.swing.JTextField();
        vDValue = new javax.swing.JTextField();
        vEValue = new javax.swing.JTextField();
        vFValue = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        programCounterValue = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        memoriaLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        opcodeValue = new javax.swing.JTextField();
        indexRegisterValue = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        delayTimerValue = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        soundTimerValue = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        clockFrequencyValue = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        memoryPanel1 = new dialogs.MemoryPanel();
        memoryPanel2 = new dialogs.MemoryPanel();
        memoryPanel3 = new dialogs.MemoryPanel();
        memoryPanel4 = new dialogs.MemoryPanel();
        memoryPanel5 = new dialogs.MemoryPanel();
        memoryPanel6 = new dialogs.MemoryPanel();
        memoryPanel7 = new dialogs.MemoryPanel();
        memoryPanel8 = new dialogs.MemoryPanel();
        memoryPanel9 = new dialogs.MemoryPanel();
        memoryPanel10 = new dialogs.MemoryPanel();
        memoryPanel11 = new dialogs.MemoryPanel();
        memoryPanel12 = new dialogs.MemoryPanel();
        memoryPanel13 = new dialogs.MemoryPanel();
        memoryPanel14 = new dialogs.MemoryPanel();
        memoryPanel15 = new dialogs.MemoryPanel();
        memoryPanel16 = new dialogs.MemoryPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estado del emulador");
        setModalityType(null);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Registros");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("V0");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("V1");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("V2");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("V3");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("V4");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("V5");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("V6");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("V7");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("V8");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("V9");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("VA");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("VB");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("VC");

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("VD");

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("VE");

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("VF");

        v0Value.setBackground(new java.awt.Color(0, 0, 0));
        v0Value.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        v0Value.setForeground(new java.awt.Color(0, 204, 51));
        v0Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v0Value.setText("00");
        v0Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v0Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v0ValueActionPerformed(evt);
            }
        });

        v1Value.setBackground(new java.awt.Color(0, 0, 0));
        v1Value.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        v1Value.setForeground(new java.awt.Color(0, 204, 51));
        v1Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v1Value.setText("00");
        v1Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        v2Value.setBackground(new java.awt.Color(0, 0, 0));
        v2Value.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        v2Value.setForeground(new java.awt.Color(0, 204, 51));
        v2Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v2Value.setText("00");
        v2Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        v2Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v2ValueActionPerformed(evt);
            }
        });

        v3Value.setBackground(new java.awt.Color(0, 0, 0));
        v3Value.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        v3Value.setForeground(new java.awt.Color(0, 204, 51));
        v3Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v3Value.setText("00");
        v3Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        v4Value.setBackground(new java.awt.Color(0, 0, 0));
        v4Value.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        v4Value.setForeground(new java.awt.Color(0, 204, 51));
        v4Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v4Value.setText("00");
        v4Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        v5Value.setBackground(new java.awt.Color(0, 0, 0));
        v5Value.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        v5Value.setForeground(new java.awt.Color(0, 204, 51));
        v5Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v5Value.setText("00");
        v5Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        v6Value.setBackground(new java.awt.Color(0, 0, 0));
        v6Value.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        v6Value.setForeground(new java.awt.Color(0, 204, 51));
        v6Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v6Value.setText("00");
        v6Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        v7Value.setBackground(new java.awt.Color(0, 0, 0));
        v7Value.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        v7Value.setForeground(new java.awt.Color(0, 204, 51));
        v7Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v7Value.setText("00");
        v7Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        v8Value.setBackground(new java.awt.Color(0, 0, 0));
        v8Value.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        v8Value.setForeground(new java.awt.Color(0, 204, 51));
        v8Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v8Value.setText("00");
        v8Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        v9Value.setBackground(new java.awt.Color(0, 0, 0));
        v9Value.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        v9Value.setForeground(new java.awt.Color(0, 204, 51));
        v9Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        v9Value.setText("00");
        v9Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        vAValue.setBackground(new java.awt.Color(0, 0, 0));
        vAValue.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        vAValue.setForeground(new java.awt.Color(0, 204, 51));
        vAValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vAValue.setText("00");
        vAValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        vBValue.setBackground(new java.awt.Color(0, 0, 0));
        vBValue.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        vBValue.setForeground(new java.awt.Color(0, 204, 51));
        vBValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vBValue.setText("00");
        vBValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        vCValue.setBackground(new java.awt.Color(0, 0, 0));
        vCValue.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        vCValue.setForeground(new java.awt.Color(0, 204, 51));
        vCValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vCValue.setText("00");
        vCValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        vDValue.setBackground(new java.awt.Color(0, 0, 0));
        vDValue.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        vDValue.setForeground(new java.awt.Color(0, 204, 51));
        vDValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vDValue.setText("00");
        vDValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        vEValue.setBackground(new java.awt.Color(0, 0, 0));
        vEValue.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        vEValue.setForeground(new java.awt.Color(0, 204, 51));
        vEValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vEValue.setText("00");
        vEValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vEValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vEValueActionPerformed(evt);
            }
        });

        vFValue.setBackground(new java.awt.Color(0, 0, 0));
        vFValue.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        vFValue.setForeground(new java.awt.Color(0, 204, 51));
        vFValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vFValue.setText("00");
        vFValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Program Counter");

        programCounterValue.setBackground(new java.awt.Color(0, 0, 0));
        programCounterValue.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        programCounterValue.setForeground(new java.awt.Color(0, 204, 51));
        programCounterValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        programCounterValue.setText("0000");
        programCounterValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Opcode");

        memoriaLabel.setBackground(new java.awt.Color(0, 0, 0));
        memoriaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        memoriaLabel.setText("Memoria");

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Index Register");

        opcodeValue.setEditable(false);
        opcodeValue.setBackground(new java.awt.Color(0, 0, 0));
        opcodeValue.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        opcodeValue.setForeground(new java.awt.Color(0, 204, 51));
        opcodeValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        opcodeValue.setText("0000");
        opcodeValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        indexRegisterValue.setBackground(new java.awt.Color(0, 0, 0));
        indexRegisterValue.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        indexRegisterValue.setForeground(new java.awt.Color(0, 204, 51));
        indexRegisterValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        indexRegisterValue.setText("0000");
        indexRegisterValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Delay Timer");

        delayTimerValue.setBackground(new java.awt.Color(0, 0, 0));
        delayTimerValue.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        delayTimerValue.setForeground(new java.awt.Color(0, 204, 51));
        delayTimerValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        delayTimerValue.setText("00");
        delayTimerValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Sound Timer");

        soundTimerValue.setBackground(new java.awt.Color(0, 0, 0));
        soundTimerValue.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        soundTimerValue.setForeground(new java.awt.Color(0, 204, 51));
        soundTimerValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        soundTimerValue.setText("00");
        soundTimerValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ic-clipart-9.png"))); // NOI18N

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Frecuencia de reloj (Hz)");

        clockFrequencyValue.setBackground(new java.awt.Color(0, 0, 0));
        clockFrequencyValue.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        clockFrequencyValue.setForeground(new java.awt.Color(0, 204, 51));
        clockFrequencyValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clockFrequencyValue.setText("0");
        clockFrequencyValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Chirp-8 Interpreter and emulator  - Visor de estado de emulación y variables del intérprete.");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Registros de estado");

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(8, 16));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(8, 16));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridLayout(16, 1));
        jPanel1.add(memoryPanel1);
        jPanel1.add(memoryPanel2);
        jPanel1.add(memoryPanel3);
        jPanel1.add(memoryPanel4);
        jPanel1.add(memoryPanel5);
        jPanel1.add(memoryPanel6);
        jPanel1.add(memoryPanel7);
        jPanel1.add(memoryPanel8);
        jPanel1.add(memoryPanel9);
        jPanel1.add(memoryPanel10);
        jPanel1.add(memoryPanel11);
        jPanel1.add(memoryPanel12);
        jPanel1.add(memoryPanel13);
        jPanel1.add(memoryPanel14);
        jPanel1.add(memoryPanel15);
        jPanel1.add(memoryPanel16);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(vFValue))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(vEValue))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(vDValue))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(vCValue))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(vBValue))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(vAValue))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(v9Value))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(v8Value))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(v7Value))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(v6Value))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(v5Value))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(v4Value))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(v3Value))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(v2Value))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(v1Value))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(v0Value, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(memoriaLabel)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(opcodeValue, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(delayTimerValue, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(soundTimerValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel20)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(indexRegisterValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel19)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel18)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(programCounterValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clockFrequencyValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(programCounterValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(opcodeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(indexRegisterValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delayTimerValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soundTimerValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clockFrequencyValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(memoriaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(v0Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(v1Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(v2Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(v3Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(v4Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(v5Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(v6Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(v7Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(v8Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(v9Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(vAValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(vBValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(vCValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(vDValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(vEValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(vFValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void v0ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v0ValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v0ValueActionPerformed

    private void v2ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v2ValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v2ValueActionPerformed

    private void vEValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vEValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vEValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatusDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatusDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatusDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatusDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StatusDialog dialog = new StatusDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clockFrequencyValue;
    private javax.swing.JTextField delayTimerValue;
    private javax.swing.JTextField indexRegisterValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel memoriaLabel;
    private dialogs.MemoryPanel memoryPanel1;
    private dialogs.MemoryPanel memoryPanel10;
    private dialogs.MemoryPanel memoryPanel11;
    private dialogs.MemoryPanel memoryPanel12;
    private dialogs.MemoryPanel memoryPanel13;
    private dialogs.MemoryPanel memoryPanel14;
    private dialogs.MemoryPanel memoryPanel15;
    private dialogs.MemoryPanel memoryPanel16;
    private dialogs.MemoryPanel memoryPanel2;
    private dialogs.MemoryPanel memoryPanel3;
    private dialogs.MemoryPanel memoryPanel4;
    private dialogs.MemoryPanel memoryPanel5;
    private dialogs.MemoryPanel memoryPanel6;
    private dialogs.MemoryPanel memoryPanel7;
    private dialogs.MemoryPanel memoryPanel8;
    private dialogs.MemoryPanel memoryPanel9;
    private javax.swing.JTextField opcodeValue;
    private javax.swing.JTextField programCounterValue;
    private javax.swing.JTextField soundTimerValue;
    private javax.swing.JTextField v0Value;
    private javax.swing.JTextField v1Value;
    private javax.swing.JTextField v2Value;
    private javax.swing.JTextField v3Value;
    private javax.swing.JTextField v4Value;
    private javax.swing.JTextField v5Value;
    private javax.swing.JTextField v6Value;
    private javax.swing.JTextField v7Value;
    private javax.swing.JTextField v8Value;
    private javax.swing.JTextField v9Value;
    private javax.swing.JTextField vAValue;
    private javax.swing.JTextField vBValue;
    private javax.swing.JTextField vCValue;
    private javax.swing.JTextField vDValue;
    private javax.swing.JTextField vEValue;
    private javax.swing.JTextField vFValue;
    // End of variables declaration//GEN-END:variables

    ArrayList<MemoryPanel> listMemoryPanels;
    int nOfPanels;
    
    public JTextField getOpcodeValue() {
        return opcodeValue;
    }

    public void setOpcodeValue(String text) {
        this.opcodeValue.setText(text);
    }

    public JTextField getProgramCounterValue() {
        return programCounterValue;
    }

    public void setProgramCounterValue(String programCounterValue) {
        this.programCounterValue.setText(programCounterValue);
    }

    public JTextField getV0Value() {
        return v0Value;
    }

    public void setV0Value(String v0Value) {
        this.v0Value.setText(v0Value);
    }

    public JTextField getV1Value() {
        return v1Value;
    }

    public void setV1Value(String v1Value) {
        this.v1Value.setText(v1Value);
    }

    public JTextField getV2Value() {
        return v2Value;
    }

    public void setV2Value(String v2Value) {
        this.v2Value.setText(v2Value);
    }

    public JTextField getV3Value() {
        return v3Value;
    }

    public void setV3Value(String v3Value) {
        this.v3Value.setText(v3Value);
    }

    public JTextField getV4Value() {
        return v4Value;
    }

    public void setV4Value(String v4Value) {
        this.v4Value.setText(v4Value);
    }

    public JTextField getV5Value() {
        return v5Value;
    }

    public void setV5Value(String v5Value) {
        this.v5Value.setText(v5Value);
    }

    public JTextField getV6Value() {
        return v6Value;
    }

    public void setV6Value(String v6Value) {
        this.v6Value.setText(v6Value);
    }

    public JTextField getV7Value() {
        return v7Value;
    }

    public void setV7Value(String v7Value) {
        this.v7Value.setText(v7Value);
    }

    public JTextField getV8Value() {
        return v8Value;
    }

    public void setV8Value(String v8Value) {
        this.v8Value.setText(v8Value);
    }

    public JTextField getV9Value() {
        return v9Value;
    }

    public void setV9Value(String v9Value) {
        this.v9Value.setText(v9Value);
    }

    public JTextField getvAValue() {
        return vAValue;
    }

    public void setVAValue(String vAValue) {
        this.vAValue.setText(vAValue);
    }

    public JTextField getvBValue() {
        return vBValue;
    }

    public void setVBValue(String vBValue) {
        this.vBValue.setText(vBValue);
    }

    public JTextField getvCValue() {
        return vCValue;
    }

    public void setVCValue(String vCValue) {
        this.vCValue.setText(vCValue);
    }

    public JTextField getvDValue() {
        return vDValue;
    }

    public void setVDValue(String vDValue) {
        this.vDValue.setText(vDValue);
    }

    public JTextField getvEValue() {
        return vEValue;
    }

    public void setVEValue(String vEValue) {
        this.vEValue.setText(vEValue);
    }

    public JTextField getvFValue() {
        return vFValue;
    }

    public void setVFValue(String vFValue) {
        this.vFValue.setText(vFValue);
    }

    public JTextField getDelayTimerValue() {
        return delayTimerValue;
    }

    public void setDelayTimerValue(String delayTimerValue) {
        this.delayTimerValue.setText(delayTimerValue);
    }

    public JTextField getIndexRegisterValue() {
        return indexRegisterValue;
    }

    public void setIndexRegisterValue(String indexRegisterValue) {
        this.indexRegisterValue.setText(indexRegisterValue);
    }

    public JTextField getSoundTimerValue() {
        return soundTimerValue;
    }

    public void setSoundTimerValue(String soundTimerValue) {
        this.soundTimerValue.setText(soundTimerValue);
    }

    public JTextField getClockFrequencyValue() {
        return clockFrequencyValue;
    }

    public void setClockFrequencyValue(String clockFrequencyValue) {
        this.clockFrequencyValue.setText(clockFrequencyValue);
    }

    public MemoryPanel getMemoryPanel1() {
        return memoryPanel1;
    }

    public void setMemoryPanel1(MemoryPanel memoryPanel1) {
        this.memoryPanel1 = memoryPanel1;
    }

    public MemoryPanel getMemoryPanel10() {
        return memoryPanel10;
    }

    public void setMemoryPanel10(MemoryPanel memoryPanel10) {
        this.memoryPanel10 = memoryPanel10;
    }

    public MemoryPanel getMemoryPanel11() {
        return memoryPanel11;
    }

    public void setMemoryPanel11(MemoryPanel memoryPanel11) {
        this.memoryPanel11 = memoryPanel11;
    }

    public MemoryPanel getMemoryPanel12() {
        return memoryPanel12;
    }

    public void setMemoryPanel12(MemoryPanel memoryPanel12) {
        this.memoryPanel12 = memoryPanel12;
    }

    public MemoryPanel getMemoryPanel13() {
        return memoryPanel13;
    }

    public void setMemoryPanel13(MemoryPanel memoryPanel13) {
        this.memoryPanel13 = memoryPanel13;
    }

    public MemoryPanel getMemoryPanel14() {
        return memoryPanel14;
    }

    public void setMemoryPanel14(MemoryPanel memoryPanel14) {
        this.memoryPanel14 = memoryPanel14;
    }

    public MemoryPanel getMemoryPanel15() {
        return memoryPanel15;
    }

    public void setMemoryPanel15(MemoryPanel memoryPanel15) {
        this.memoryPanel15 = memoryPanel15;
    }

    public MemoryPanel getMemoryPanel16() {
        return memoryPanel16;
    }

    public void setMemoryPanel16(MemoryPanel memoryPanel16) {
        this.memoryPanel16 = memoryPanel16;
    }

    public MemoryPanel getMemoryPanel2() {
        return memoryPanel2;
    }

    public void setMemoryPanel2(MemoryPanel memoryPanel2) {
        this.memoryPanel2 = memoryPanel2;
    }

    public MemoryPanel getMemoryPanel3() {
        return memoryPanel3;
    }

    public void setMemoryPanel3(MemoryPanel memoryPanel3) {
        this.memoryPanel3 = memoryPanel3;
    }

    public MemoryPanel getMemoryPanel4() {
        return memoryPanel4;
    }

    public void setMemoryPanel4(MemoryPanel memoryPanel4) {
        this.memoryPanel4 = memoryPanel4;
    }

    public MemoryPanel getMemoryPanel5() {
        return memoryPanel5;
    }

    public void setMemoryPanel5(MemoryPanel memoryPanel5) {
        this.memoryPanel5 = memoryPanel5;
    }

    public MemoryPanel getMemoryPanel6() {
        return memoryPanel6;
    }

    public void setMemoryPanel6(MemoryPanel memoryPanel6) {
        this.memoryPanel6 = memoryPanel6;
    }

    public MemoryPanel getMemoryPanel7() {
        return memoryPanel7;
    }

    public void setMemoryPanel7(MemoryPanel memoryPanel7) {
        this.memoryPanel7 = memoryPanel7;
    }

    public MemoryPanel getMemoryPanel8() {
        return memoryPanel8;
    }

    public void setMemoryPanel8(MemoryPanel memoryPanel8) {
        this.memoryPanel8 = memoryPanel8;
    }

    public MemoryPanel getMemoryPanel9() {
        return memoryPanel9;
    }

    public void setMemoryPanel9(MemoryPanel memoryPanel9) {
        this.memoryPanel9 = memoryPanel9;
    }
    
    public void setMemoryValues(final int[] memoria) {
        
        long t1 = System.nanoTime();
        
        for (int i = 0; i < nOfPanels; i++) {
            //long t3 = System.nanoTime();
            listMemoryPanels.get(i).setMemoryValues(memoria, i);
            //long t4 = System.nanoTime();
            //System.out.println("demora setMemoryValues para MemoryPanel" + i + ": " + (t4 - t3));
        }
        
        long t2 = System.nanoTime();
        
        System.out.println("demora setMemoryValues: " + (t2 - t1));
    }

    // Obtener todos los componentes de tipo MemoryPanel del contenedor
    private List<MemoryPanel> getAllMemoryPanelComponents(final Container c) {
        long t1 = System.nanoTime();
        Component[] comps = c.getComponents();
        
        List<MemoryPanel> compList = new ArrayList<>();
        
        for (Component comp : comps) {
            
            if (comp instanceof MemoryPanel) {
                compList.add((MemoryPanel) comp);
            }
            
        }
        
        long t2 = System.nanoTime();
        
        //compList.sort(new SortMemoryPanelByName());
        
        System.out.println("demora getAllMemoryPanelComponents: " + (t2 - t1));

        return compList;
    }

    class SortMemoryPanelByName implements Comparator<MemoryPanel> {

        @Override
        public int compare(MemoryPanel m1, MemoryPanel m2) {
            //return (o1.getName().compareTo(o2.getName()));
            return m1.getName().compareTo(m2.getName());
        }
    }

}
